title: Nathan Chen
logo: /assets%20img/20251225_153516.jpg
description: Aspiring Data Scientist with internship experience across SaaS, AI, and FoodTech. Recent Data Science graduate from UC Berkeley. Passionate about AI. US Citizen.
show_donwloads: true
theme: jekyll-theme-minimal
